# Generated by Django 2.1.4 on 2019-01-18 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='room_code',
            field=models.CharField(default='ABCDEF', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
